scriptencoding utf-8
set enc=utf-8
set fileencoding=utf-8
set encoding=utf-8
set fileformats=unix,dos
set fileformat=unix
" Text formatting
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
filetype plugin indent on

" Editing settings
set nocompatible " no Vi compatibility mode
set incsearch " search as characters are entered
set hlsearch  " highlight matches
" to clear the highlights from the last search
nnoremap <leader><space> :nohlsearch<CR>
if has("win32") || has("win64")
	set undodir=$HOME\\.vim\\undo,$TEMP
	set directory=$HOME\\.vim\\directory,$TEMP
	set backupdir=$HOME\\.vim\\backup,$TEMP
	set backupskip=$TEMP
else
	set undodir=~/.vim/undo,/tmp
	set directory=~/.vim/directory,/tmp
	set backupdir=~/.vim/backup,/tmp
	set backupskip=/tmp
endif
set showcmd

" Visual elements
syntax enable
"set showtabline=2
set ruler
set number
set showcmd
set cursorline
set lazyredraw
set wildmenu
set showmatch
set listchars=tab:»\ ,nbsp:~,precedes:»,extends:«,trail:_
set nolist

" maybe map it to comma later...
"let mapleader=","
nmap <leader>w :w!<CR>
nmap <leader>p :set paste!<CR>
nmap <leader>l :set list!<CR>
nmap <leader>t :set expandtab!<CR>
nmap <silent> <leader>n :set number!<CR>

set path+=**

augroup jenkins
    autocmd!
	autocmd BufNewFile,BufRead Jenkinsfile setf groovy
augroup END

augroup makefiles
    autocmd!
    autocmd BufEnter Makefile setlocal noexpandtab
augroup END

augroup yamlfiles
	autocmd!
	autocmd BufNewFile,BufRead *.yaml,*.yml set filetype=yaml
augroup END
